---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html
    - >
      rsync -av --delete
      --exclude='.git'
      --exclude='.gitignore'
      --exclude='.cpanel.yml'
      --exclude='.DS_Store'
      --exclude='config.example.php'
      --exclude='README.txt'
      ./ $DEPLOYPATH/
